# Generated by Django 4.0.6 on 2022-10-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Назва посту')),
                ('smallDescriptions', models.TextField(verbose_name='Короткий опис максимум 30 символів')),
                ('content', models.TextField(verbose_name='Основний вміст посту')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
